name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud_frontend:
    name: SonarCloud Analysis - Front-end
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Front-end Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: front  # Spécifie le répertoire front-end

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install
        working-directory: ./front

      - name: Run Tests
        run: npm test -- --no-fail-on-empty-test-suite || true
        working-directory: ./front

      - name: Upload Test Coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: ./front/coverage

      - name: SonarCloud Scan - Front-end
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: front
          args: >
            -Dsonar.organization=beyealioune1
            -Dsonar.projectKey=beyealioune1_beyealioune
            env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  sonarcloud_backend:
    name: SonarCloud Analysis - Back-end
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Back-end Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: back  # Spécifie le répertoire back-end

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Build and Test with Maven
        run: |
          cd back
          mvn -B clean verify
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io

      - name: SonarCloud Scan - Back-end
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: back
          args: >
            -Dsonar.organization=beyealioune1
            -Dsonar.projectKey=beyealioune1_beyealioune
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: [sonarcloud_frontend, sonarcloud_backend]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # Ajoutez les étapes pour construire et déployer votre application

