name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests_frontend:
    name: Tests Frontend et Analyse SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code source du Frontend
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: front

      - name: Configurer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Installer les dépendances
        run: npm ci
        working-directory: front

      - name: Exécuter les tests Frontend et générer le rapport de couverture
        run: npm test -- --watch=false --browsers=ChromeHeadless --code-coverage
        working-directory: front

      - name: Téléverser le rapport de couverture du Frontend
        uses: actions/upload-artifact@v2
        with:
          name: rapport-coverage-frontend
          path: front/coverage

      - name: Analyse SonarCloud - Frontend
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: front
          args: >
            -Dsonar.organization=beyealioune1
            -Dsonar.projectKey=beyealioune1_beyealioune
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          
  backend_tests:
    name: Backend Tests, Jacoco Report, and SonarCloud Analysis
    runs-on: ubuntu-latest
    needs: tests_frontend

    steps:
      - name: Checkout Backend Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: back

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Build and Test Backend
        run: mvn clean verify
        working-directory: back

      - name: Generate Jacoco Report
        run: mvn jacoco:report
        working-directory: back

      - name: Upload Jacoco Report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: back/target/site/jacoco

      - name: SonarCloud Scan - Backend
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: back
          args: >
            -Dsonar.organization=beyealioune1
            -Dsonar.projectKey=beyealioune1_beyealioune
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  publish_docker_hub:
    name: Publish Docker Images
    runs-on: ubuntu-latest
    needs: [tests_frontend, backend_tests]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Frontend Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./front
          file: ./front/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/frontend-image:latest

      - name: Build and Push Backend Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./back
          file: ./back/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/backend-image:latest
